{% set name = "popclass" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/popclass-{{ version }}.tar.gz
  sha256: bc55c807da9c87d4d7014c90b1746d44936be62773fb86bf45ffc268e65dc7c2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - scipy
    - numpy
    - asdf
    - matplotlib-base

test:
  imports:
    - popclass
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/LLNL/popclass
  summary: A python package for classifying microlensing events
  license: MIT
  license_file:
    - LICENSE
    - NOTICE
  doc_url: https://popclass.readthedocs.io/
  dev_url: https://github.com/LLNL/popclass

extra:
  recipe-maintainers:
    - astrophpeter
